name:                UnitCalc
version:             0.1.0.0
github:              "abethel/UnitCalc"
license:             BSD3
author:              "Alex Bethel"
maintainer:          "abethel@cs.nmt.edu"
copyright:           "Copyright (c) 2022 by Alex Bethel. Licensed under the GNU GPL version 3 or later; see LICENSE for details."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            unknown

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/abethel/UnitCalc#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- parsec

library:
  source-dirs: src

executables:
  UnitCalc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - UnitCalc

tests:
  UnitCalc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - UnitCalc
